### ISSUE TITLE
Don't hard code data where possible

### ISSUE THREAD

**Issue by andrew-boyd** [AtticusRoberts/weather#3]
In your primary App.vue file you're hardcoding the airport codes and manually authoring a `place` component for each. The provided API has an endpoint you can hit to retrieve all airports. 

Using the response data from that call it should be possible to loop over them and dynamically output the `place` elements. Given that you're trying to spatially place them on a map you'll still need a seperate dictionary object in your code for the coordinates of all known airports that will be represented in the API response.

**Comment by AtticusRoberts** [comment]
Should be dynamic now
